spring.application.name=controle-financeiro

spring.datasource.url=jdbc:postgresql://localhost:5432/financeiro
spring.datasource.username=financeiro_user
spring.datasource.password=financeiro_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.web.error.include-message=always

spring.security.user.name=guilherme
spring.security.user.password=26022023Nyx